# roles_data.py

ROLES_DATA = [
    {"id": "afa", "name": "Advanced Forward - Attack (afa)"},
    {"id": "apa", "name": "Advanced Playmaker - Attack (apa)"},
    {"id": "aps", "name": "Advanced Playmaker - Support (aps)"},
    {"id": "ad", "name": "Anchor - Defend (ad)"},
    {"id": "ama", "name": "Attacking Midfielder - Attack (ama)"},
    {"id": "ams", "name": "Attacking Midfielder - Support (ams)"},
    {"id": "bpdc", "name": "Ball Playing Defender - Cover (bpdc)"},
    {"id": "bpdd", "name": "Ball Playing Defender - Defend (bpdd)"},
    {"id": "bpds", "name": "Ball Playing Defender - Stopper (bpds)"},
    {"id": "bwmd", "name": "Ball Winning Midfielder - Defend (bwmd)"},
    {"id": "bwms", "name": "Ball Winning Midfielder - Support (bwms)"},
    {"id": "b2bs", "name": "Box to Box Midfielder - Support (b2bs)"},
    {"id": "cars", "name": "Carrilero - Support (cars)"},
    {"id": "cdc", "name": "Central Defender - Cover (cdc)"},
    {"id": "cdd", "name": "Central Defender - Defend (cdd)"},
    {"id": "cds", "name": "Central Defender - Stopper (cds)"},
    {"id": "cma", "name": "Central Midfielder - Attack (cma)"},
    {"id": "cmd", "name": "Central Midfielder - Defend (cmd)"},
    {"id": "cms", "name": "Central Midfielder - Support (cms)"},
    {"id": "cfa", "name": "Complete Forward - Attack (cfa)"},
    {"id": "cfs", "name": "Complete Forward - Support (cfs)"},
    {"id": "cwba", "name": "Complete Wingback - Attack (cwba)"},
    {"id": "cwbs", "name": "Complete Wingback - Support (cwbs)"},
    {"id": "dlfa", "name": "Deep Lying Forward - Attack (dlfa)"},
    {"id": "dlfs", "name": "Deep Lying Forward - Support (dlfs)"},
    {"id": "dlpd", "name": "Deep Lying Playmaker - Defend (dlpd)"},
    {"id": "dlps", "name": "Deep Lying Playmaker - Support (dlps)"},
    {"id": "dmd", "name": "Defensive Midfielder - Defend (dmd)"},
    {"id": "dms", "name": "Defensive Midfielder - Support (dms)"},
    {"id": "dwd", "name": "Defensive Winger - Defend (dwd)"},
    {"id": "dws", "name": "Defense Winger - Support (dws)"},
    {"id": "engs", "name": "Enganche - Support (engs)"},
    {"id": "f9s", "name": "False Nine - Support (f9s)"},
    {"id": "fba", "name": "Fullback - Attack (fba)"},
    {"id": "fbd", "name": "Fullback - Defend (fbd)"},
    {"id": "fbs", "name": "Fullback - Support (fbs)"},
    {"id": "gkd", "name": "GK - Defend (gkd)"},
    {"id": "hbd", "name": "Half Back - Defend (hbd)"},
    {"id": "ifa", "name": "Inside Forward - Attack (ifa)"},
    {"id": "ifs", "name": "Inside Forward - Support (ifs)"},
    {"id": "ifbd", "name": "Inverted Fullback - Defend (ifbd)"},
    {"id": "iwa", "name": "Inverted Winger - Attack (iwa)"},
    {"id": "iws", "name": "Inverted Winger - Support (iws)"},
    {"id": "iwba", "name": "Inverted Wingback - Attack (iwba)"},
    {"id": "iwbd", "name": "Inverted Wingback - Defend (iwbd)"},
    {"id": "iwbs", "name": "Inverted Wingback - Support (iwbs)"},
    {"id": "ld", "name": "Libero - Defend (ld)"},
    {"id": "ls", "name": "Libero - Support (ls)"},
    {"id": "meza", "name": "Mezzala - Attack (meza)"},
    {"id": "mezs", "name": "Mezzala - Support (mezs)"},
    {"id": "ncbc", "name": "No-Nonsense Centreback - Cover (ncbc)"},
    {"id": "ncbd", "name": "No-Nonsense Centreback - Defend (ncbd)"},
    {"id": "ncbs", "name": "No-Nonsense Centreback - Stopper (ncbs)"},
    {"id": "nfbd", "name": "No-Nonsense Fullback - Defend (nfbd)"},
    {"id": "pa", "name": "Poacher - Attack (pa)"},
    {"id": "pfa", "name": "Pressing Forward- Attack (pfa)"},
    {"id": "pfd", "name": "Pressing Forward - Defend (pfd)"},
    {"id": "pfs", "name": "Pressing Forward - Support (pfs)"},
    {"id": "raua", "name": "Raumdeuter - Attack (raua)"},
    {"id": "regs", "name": "Regista - Support (regs)"},
    {"id": "rps", "name": "Roaming Playmaker - Support (rps)"},
    {"id": "sva", "name": "Segundo Volante - Attack (sva)"},
    {"id": "svs", "name": "Segundo Volante - Support (svs)"},
    {"id": "ssa", "name": "Shadow Striker - Attack (ssa)"},
    {"id": "ska", "name": "Sweeper Keeper - Attack (ska)"},
    {"id": "skd", "name": "Sweeper Keeper - Defend (skd)"},
    {"id": "sks", "name": "Sweeper Keeper - Support (sks)"},
    {"id": "tfa", "name": "Target Forward - Attack (tfa)"},
    {"id": "tfs", "name": "Target Forward - Support (tfs)"},
    {"id": "trea", "name": "Trequartista - Attack (trea)"},
    {"id": "wcba", "name": "Wide Centreback - Attack (wcba)"},
    {"id": "wcbd", "name": "Wide Centreback - Defend (wcbd)"},
    {"id": "wcbs", "name": "Wide Centreback - Support (wcbs)"},
    {"id": "wma", "name": "Wide Midfielder - Attack (wma)"},
    {"id": "wmd", "name": "Wide Midfielder - Defend (wmd)"},
    {"id": "wms", "name": "Wide Midfielder - Support (wms)"},
    {"id": "wpa", "name": "Wide Playmaker - Attack (wpa)"},
    {"id": "wps", "name": "Wide Playmaker - Support (wps)"},
    {"id": "wtfa", "name": "Wide Target Forward - Attack (wtfa)"},
    {"id": "wtfs", "name": "Wide Target Forward - Support (wtfs)"},
    {"id": "wa", "name": "Winger - Attack (wa)"},
    {"id": "ws", "name": "Winger - Support (ws)"},
    {"id": "wba", "name": "Wingback - Attack (wba)"},
    {"id": "wbd", "name": "Wingback - Defend (wbd)"},
    {"id": "wbs", "name": "Wingback - Support (wbs)"},
]
